DROP DATABASE IF EXISTS jurilog;
CREATE DATABASE IF NOT EXISTS jurilog;
USE jurilog;


CREATE USER IF NOT EXISTS 'root' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON jurilog . * TO 'root';

CREATE TABLE client(
   id int NOT NULL,
   PRIMARY KEY (id),
   nom VARCHAR(255) NOT NULL,
   prenom VARCHAR(255) NOT NULL,
   adresse VARCHAR(255) NOT NULL,
   phone VARCHAR(255) NOT NULL,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL
);